# Generated by Django 3.0.2 on 2020-01-29 05:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 1, 29, 5, 19, 42, 316934))),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Category')),
            ],
        ),
    ]
